# Generated by Django 3.0.3 on 2020-07-11 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('citykurwaid', models.IntegerField()),
                ('coordlon', models.FloatField()),
                ('coordlat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_feels', models.FloatField()),
                ('pressure', models.FloatField()),
                ('weather_main', models.CharField(max_length=32)),
                ('weather_desc', models.CharField(max_length=64)),
                ('weather_icon', models.CharField(max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_stats.City')),
            ],
        ),
    ]
