# Generated by Django 3.0.3 on 2020-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='citykurwaid',
            new_name='cityid',
        ),
    ]
